### ISSUE TITLE
Android Studio preview problem

### ISSUE THREAD

**Issue by renyanxu2000** [Piasy/ShapedDraweeView#2]
java.lang.NullPointerException
    at android.graphics.Canvas_Delegate.restoreTo(Canvas_Delegate.java:1132)
    at android.graphics.Canvas_Delegate.native_restoreToCount(Canvas_Delegate.java:256)
    at android.graphics.Canvas.native_restoreToCount(Canvas.java)
    at android.graphics.Canvas.restoreToCount(Canvas.java:548)
    at android.view.View.draw(View.java:17005)
    at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
    at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:16974)
    at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
    at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:16974)
    at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
    at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:16974)
    at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
    at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:16974)
    at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3764)
    at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:61)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3764)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3550)
    at android.view.View.draw(View.java:17071)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:387)
    at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:498)
    at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:434)
    at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:350)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:520)
    at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:508)
    at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:967)
    at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:508)
    at com.android.tools.idea.rendering.RenderTask.access$600(RenderTask.java:75)
    at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:620)
    at com.android.tools.idea.rendering.RenderTask$3.call(RenderTask.java:617)
    at com.android.tools.idea.rendering.RenderService.runRenderAction(RenderService.java:371)
    at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:617)
    at com.android.tools.idea.rendering.RenderTask.render(RenderTask.java:639)
    at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.doRender(AndroidLayoutPreviewToolWindowManager.java:654)
    at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager.access$1700(AndroidLayoutPreviewToolWindowManager.java:82)
    at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7$1.run(AndroidLayoutPreviewToolWindowManager.java:596)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at org.jetbrains.android.uipreview.AndroidLayoutPreviewToolWindowManager$7.run(AndroidLayoutPreviewToolWindowManager.java:591)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:337)
    at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:327)
    at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:271)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:286)
    at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:244)
    at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
    at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
    at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Piasy** [comment]
我还以为你的 AS 崩了。

使用 `1.2.1`，就不会有错误了，但是依然没有预览，23333

**Comment by renyanxu2000** [comment]
用的就是1.2.1啊
导致我的AS都不能预览其它文件了。。。。。

**Comment by Piasy** [comment]
AS 什么版本？我的 2.2 RC 没问题。

不过这不是什么问题，不影响开发的话可以忽略。

**Comment by renyanxu2000** [comment]
我AS版本2.1.3

**Comment by Piasy** [comment]
嗯，就是 IDE 的问题。

> 不过这不是什么问题，不影响开发的话可以忽略。
